### ISSUE TITLE
There are no endpoints that match the Policy Id username

### ISSUE THREAD

**Issue by TheVexy** [fledge-iot/fledge-south-s2opcua#60]
I've notice this happening only on some opc ua servers not all

In the function `PolicyIdToUserTokenType`, the code compares the given `policyId` to predefined strings `"anonymous"` and `"username"` to determine the correct `OpcUa_UserTokenType`. Comparisons are done using `strncmp`, a function that is case-sensitive. If the `policyId` is `"Username"` with a capital "U", it will not match the string `"username"` due to the difference in case.

https://github.com/fledge-iot/fledge-south-s2opcua/blob/fa8aafff0e947a5379ad92100431bc9954b85748/opcua.cpp#L72

<img width="379" alt="image" src="https://github.com/fledge-iot/fledge-south-s2opcua/assets/36013759/4db89ad6-57a1-437b-ba29-601aa422efc3">
<img width="652" alt="image" src="https://github.com/fledge-iot/fledge-south-s2opcua/assets/36013759/d0780fe2-9793-432c-baa7-639500246a84">

**Comment by RVerhoeff** [comment]
I believe this is the same problem as was reported by another user in the _Fledge_ issues list: [#1272: South s2opcua not working with Security None and User Authentication username](https://github.com/fledge-iot/fledge/issues/1272). In a nutshell, the [S2OPC Toolkit](https://systerel.gitlab.io/S2OPC/index.html) we are using does not allow username/password authentication with Security Mode of _None_ and Security Policy of _None_. This would give the appearance of security but would actually transmit passwords over the wire in clear text. I wrote a detailed explanation at the bottom of the Fledge Issue #1272 page.

**Comment by RVerhoeff** [comment]
In the function `PolicyIdToUserTokenType`, the code does indeed perform a case-sensitive comparison on the passed strings. The strings, however, come from the _User Authentication Policy_ configuration drop-down on the Fledge GUI. This is a Fledge enumeration which can only have the values `anonymous` and `username`. User policy strings obtained from the OPC UA server's endpoints are never passed to the `PolicyIdToUserTokenType` method.

**Comment by TheVexy** [comment]
@RVerhoeff   To avoid the mismatch I deleted the last if's condition (opcua.cpp, line 1410):
if (userIds[j].tokenType == tokenType &&
	userIds[j].securityPolicyUri &&
	!strcmp(userIds[j].securityPolicyUri, security.security_policy))
{
	matchedPolicyId = true;
}
That fixed the policy mismatch, resulting with the following error:
May 28 08:24:12 e56e1b56272a Fledge softing[1842]: ERROR: Failed to create OPC/UA connection to server opc.tcp://172.28.70.3:4897/Softing/dataFEED/Server, connection failed
It is unclear how to check why that error occurs and the logs of the softing software are not helpful with that.


It seems that the softing server provides false information about the security policy, and therefore the policy mismatch is not the actual problem.. 

Any insights on what further steps I could take to debug this?

**Comment by RVerhoeff** [comment]
It could be a mismatch between the Security Policy for the endpoint and the Security Policy for the _UserIdentityToken_. I wrote an explanation of what this means in the [Fledge Issue #1272](https://github.com/fledge-iot/fledge/issues/1272) page. In the OPC UA standard, these two policies are separate but in S2OPC, they must match. If they don't, the Toolkit will not allow a connection and you will get the message above. To troubleshoot this, go to the _Advanced Configuration_ tag in your S2OPCUA South instance page and set _Minimum Log Level_ to _Debug_. Attempt a connection which will fail. Read the _/var/log/syslog_ file. Look for the string _OPC UA Server has 'n' endpoints_. This begins the logging of the characteristics of each endpoint exposed by your OPC UA server. One block of log file lines on my system looks like this:
![image](https://github.com/fledge-iot/fledge-south-s2opcua/assets/7538009/b419230b-4998-4472-9a2b-28a83441cd30)

The first integer on each line is the endpoint number. My configuration has 5 endpoints so this is the last one. The first 5 lines of this section are the characteristics of the endpoint (BTW, on your system, you will see the number '2' next to _security mode_. The keyword _Sign_ is from a new github branch that has not been released yet). Starting on the 6th line, the code iterates through all user identity policies that are supported on the endpoint; you will see a second integer at the beginning of each line that counts each user policy.

When searching for a usable endpoint, the code checks if the endpoint security policy Uri (line 4) matches any of the user identity security policy Uris (lines 10, 15 and 20). They must match. In this screenshot, this endpoint is unusable because the endpoint security policy _#Basic256Sha256_ does not match any of the 3 user identity policies _#Basic256_, _null_ or _#Basic128Rsa15_.

**Comment by TheVexy** [comment]
My server configuration 
<img width="785" alt="image" src="https://github.com/fledge-iot/fledge-south-s2opcua/assets/36013759/0daf2a65-2842-4ae8-9f1f-e59aa440df33">

With annonymous + sign and encrypt it does work and I do get readings
<img width="763" alt="image" src="https://github.com/fledge-iot/fledge-south-s2opcua/assets/36013759/4e0f1380-353c-4bb4-a83d-129a7e7178a9">


When enabling username&password with all possible combinations the plugins allow I still do not succeed to connect 

`May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: WARNING: Not connected to OPC/UA Server: opc.tcp://172.100.10.10:4897/Softing/dataFEED/Server

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: ERROR: There are no endpoints that match the Policy Id username

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: ERROR: Failed to match any server endpoints with Security Mode 'Sign & Encrypt', Security Policy 'http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256', Authentication policy 'username'

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5: 'username' != 'Username_Policy' (1)

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5: 'username' != 'Certificate_Policy' (2)

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5: 'username' != 'Anonymous_Policy' (0)

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5: checking user ID tokens

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: Endpoint 5 matches on security policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: Endpoint 5 matches on security mode Sign & Encrypt

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 4: security policy mismatch http://opcfoundation.org/UA/SecurityPolicy#Basic256 != http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: Endpoint 4 matches on security mode Sign & Encrypt

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 3: security policy mismatch http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15 != http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: Endpoint 3 matches on security mode Sign & Encrypt

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 2: security mode does not match Sign & Encrypt

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 1: security mode does not match Sign & Encrypt

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 0: security mode does not match Sign & Encrypt

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: Endpoint matching starting....

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: INFO: Using Client Key /usr/local/fledge/data/etc/certs/Helinkey.pem

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: INFO: Using Client Certificate /usr/local/fledge/data/etc/certs/Helincert.der

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: INFO: Using Server Certificate /usr/local/fledge/data/etc/certs/SoftingOpcUaEndpoint[4D6DC3404361A3AAE9C3D1AAF9BBCADA8E848A9C].der

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: WARNING: No Certificate Revocation List has been configured

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: WARNING: No CA Certificate has been configured

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: Requesting username authentication policy

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: Requesting Security Mode 'Sign & Encrypt', Security Policy 'http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256'

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 2 - security policy Uri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 2 - issuer endpoint Url: (null)

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 2 - issued token type: (null)

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 2 - token type: 1

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 2 - policy Id: Username_Policy

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 1 - security policy Uri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 1 - issuer endpoint Url: (null)

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 1 - issued token type: (null)

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 1 - token type: 2

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 1 - policy Id: Certificate_Policy

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 0 - security policy Uri: (null)

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 0 - issuer endpoint Url: (null)

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 0 - issued token type: (null)

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 0 - token type: 0

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 0 - policy Id: Anonymous_Policy

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 - transport profile Uri: http://opcfoundation.org/UA-Profile/Transport/uatcp-uasc-uabinary

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 - security policy Uri: http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 - security mode: 3

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 - security level: 53

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 5 - url: opc.tcp://172.100.10.10:4897/Softing/dataFEED/Server

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 4 2 - security policy Uri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 4 2 - issuer endpoint Url: (null)

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 4 2 - issued token type: (null)

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 4 2 - token type: 1

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 4 2 - policy Id: Username_Policy

May 30 11:26:30 bd44f6e16478 Fledge test1[11024]: DEBUG: 4 1 - security policy Uri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15`

**Comment by TheVexy** [comment]
Is the  http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15 automatically asigned when we select Username&Password in the plugin?

**Comment by TheVexy** [comment]
@RVerhoeff I turned on Basic128Rsa15 on the endpoint security policy but still get the same error,
<img width="781" alt="image" src="https://github.com/fledge-iot/fledge-south-s2opcua/assets/36013759/ef7ed233-5bdb-4436-a5bc-74e69d2c1b25">

 or perhaps I missunderstood and it's on the server that Security Policy for the UserIdentityToken it's set? 

```
May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: WARNING: Not connected to OPC/UA Server: opc.tcp://172.100.10.10:4897/Softing/dataFEED/Server

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: ERROR: There are no endpoints that match the Policy Id username

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: ERROR: Failed to match any server endpoints with Security Mode 'Sign & Encrypt', Security Policy 'http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256', Authentication policy 'username'

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 2: 'username' != 'Username_Policy' (1)

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 2: checking user ID tokens

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: Endpoint 2 matches on security policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: Endpoint 2 matches on security mode Sign & Encrypt

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 1: security policy mismatch http://opcfoundation.org/UA/SecurityPolicy#Basic256 != http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: Endpoint 1 matches on security mode Sign & Encrypt

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 0: security policy mismatch http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15 != http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: Endpoint 0 matches on security mode Sign & Encrypt

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: Endpoint matching starting....

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: INFO: Using Client Key /usr/local/fledge/data/etc/certs/Helinkey.pem

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: INFO: Using Client Certificate /usr/local/fledge/data/etc/certs/Helincert.der

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: INFO: Using Server Certificate /usr/local/fledge/data/etc/certs/SoftingOpcUaEndpoint[4D6DC3404361A3AAE9C3D1AAF9BBCADA8E848A9C].der

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: WARNING: No Certificate Revocation List has been configured

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: WARNING: No CA Certificate has been configured

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: Requesting username authentication policy

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: Requesting Security Mode 'Sign & Encrypt', Security Policy 'http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256'

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 2 0 - security policy Uri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 2 0 - issuer endpoint Url: (null)

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 2 0 - issued token type: (null)

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 2 0 - token type: 1

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 2 0 - policy Id: Username_Policy

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 2 - transport profile Uri: http://opcfoundation.org/UA-Profile/Transport/uatcp-uasc-uabinary

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 2 - security policy Uri: http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 2 - security mode: 3

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 2 - security level: 53

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 2 - url: opc.tcp://172.100.10.10:4897/Softing/dataFEED/Server

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 1 0 - security policy Uri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 1 0 - issuer endpoint Url: (null)

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 1 0 - issued token type: (null)

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 1 0 - token type: 1

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 1 0 - policy Id: Username_Policy

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 1 - transport profile Uri: http://opcfoundation.org/UA-Profile/Transport/uatcp-uasc-uabinary

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 1 - security policy Uri: http://opcfoundation.org/UA/SecurityPolicy#Basic256

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 1 - security mode: 3

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 1 - security level: 13

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 1 - url: opc.tcp://172.100.10.10:4897/Softing/dataFEED/Server

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 0 0 - security policy Uri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 0 0 - issuer endpoint Url: (null)

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 0 0 - issued token type: (null)

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 0 0 - token type: 1

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 0 0 - policy Id: Username_Policy

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 0 - transport profile Uri: http://opcfoundation.org/UA-Profile/Transport/uatcp-uasc-uabinary

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 0 - security policy Uri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 0 - security mode: 3

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 0 - security level: 8

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: 0 - url: opc.tcp://172.100.10.10:4897/Softing/dataFEED/Server

May 30 11:54:52 bd44f6e16478 Fledge test1[19138]: DEBUG: OPC/UA Server has 3 endpoints
```

**Comment by TheVexy** [comment]
I belive the server set's the  SecurityPolicy of the UserTokenPolicy to #Basic128Rsa15 hence the inital error

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: Requesting username authentication policy

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: Requesting Security Mode 'Sign', Security Policy 'http://opcfoundation.org/UA/SecurityPolicy#Basic256'

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: 0 1 - security policy Uri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: 0 1 - issuer endpoint Url: (null)

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: 0 1 - issued token type: (null)

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: 0 1 - token type: 1

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: 0 1 - policy Id: Username_Policy

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: 0 0 - security policy Uri: http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: 0 0 - issuer endpoint Url: (null)

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: 0 0 - issued token type: (null)

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: 0 0 - token type: 2

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: 0 0 - policy Id: Certificate_Policy

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: 0 - transport profile Uri: http://opcfoundation.org/UA-Profile/Transport/uatcp-uasc-uabinary

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: 0 - security policy Uri: http://opcfoundation.org/UA/SecurityPolicy#Basic256

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: 0 - security mode: 2

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: 0 - security level: 12

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: 0 - url: opc.tcp://172.100.10.10:4897/Softing/dataFEED/Server

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: OPC/UA Server has 1 endpoints

May 30 13:05:39 bd44f6e16478 Fledge test1[25901]: DEBUG: SOPCInit Start

**Comment by RVerhoeff** [comment]
You are correct: the OPC UA server sets the _SecurityPolicy_ of the _UserTokenPolicy_. An OPC UA client (that is, the plugin) can read it but not change it. The Softing server sets the _SecurityPolicy_ of the _UserTokenPolicy_ to _#Basic128Rsa15_. This is an odd choice because this Security Policy has been deprecated by the OPC Foundation (See [OPC UA Specification, Part 7, Section 6.6.162](https://reference.opcfoundation.org/Core/Part7/v104/docs/6.6.162)). We cannot change code to accommodate this older Policy because the S2OPC Toolkit does not support it (check file _/usr/local/include/s2opc/common/sopc_crypto_profiles.h_ on your system and look for _SOPC_SecurityPolicy_ID_).

From your screenshot of the Softing configuration dialog, it looks like you can't configure the _SecurityPolicy_ of the _UserTokenPolicy_ (we use the [Prosys Simulation Server](https://prosysopc.com/products/opc-ua-simulation-server/) for testing; it can't either). I suggest contacting Softing to ask if there is a way to modify the _SecurityPolicy_ of the _UserTokenPolicy_.

**Comment by TheVexy** [comment]
Thank you so much for your support and detailed explanations. They were incredibly helpful in troubleshooting the issue. 🍾 
This GitHub issue can be closed.
